### ISSUE TITLE
Please Release 0.2.2 :)

### ISSUE THREAD

**Issue by talk2MeGooseman** [stevehodges/talk_like_a_pirate#7]
Hey @stevehodges , I noticed that 0.2.2 hasn't been released yet. I wanted to give you a heads up! Let me know when you get around to release. Thanks!

**Comment by mslinn** [comment]
```
depends on
        activesupport (>= 3.0.0, < 6.0.0)
```
But that be too ole fer our modern world. Please release an update, or ye will be keelhauled. Arrgh! 

My demo needs activesupport = 7.0.2.3

**Comment by stevehodges** [comment]
@mslinn Aye, matey! When me crew's in port we'll upgrade th' ship! From th' maps we spy a port a day or two  out.

**Comment by stevehodges** [comment]
@mslinn  0.2.2 can now b' found on RubyGems. 0.2.3 coming soon t' enterrrr  th' modern day

**Comment by mslinn** [comment]
Shiver me timbers, that was fast. I thank ye. Next time ye sail by Montreal, let me buy ye rum.

**Comment by mslinn** [comment]
I will check it out after I get back from the gym, and run an errand.

**Comment by mslinn** [comment]
The new branch works. Here be a screenshot o' me [wee demo](https://github.com/mslinn/jekyll_plugin_template/tree/master/demo). BTW, I always thought o' Canada as "The Great White North", nah "Great North".

![2022-04-11_16-59-04](https://user-images.githubusercontent.com/485818/162831792-a10dc583-39c1-47c5-8a12-ba198b6dbdb0.png)

**Comment by stevehodges** [comment]
@mslinn 0.2.3 has been released and can be installed in Rails 7 projects.
